name: Lint check

on:
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.github/workflows/check-format.yml'
      - '.clang-format'

jobs:
  check-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        extensions: 'hpp, cpp, h'
        clangFormatVersion: 12
        inplace: False
