name: Run tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: h4570/tyra-test
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd engine
          make test SRCDIR=src/test INCDIR=inc/test EE_PREFIX= || true
          ./bin/tests.elf --success=true --reporters=junit --out=./tests.xml
      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Tyra tests
          reporter: java-junit
          path: ./tests.xml