name: Run tests

on: [ push, pull_request ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: h4570/tyra-test
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container